### ISSUE TITLE
`tabs` 风格与官方 `code-group` 不相符

### ISSUE THREAD

**Issue by Suomm** [sapphi-red/vitepress-plugins#45] opened 2023-11-22 14:25 UTC
`tabs` style does not match the official `code-group`.

**Comment by Suomm** [comment] 2023-11-22 14:30
![image](https://github.com/sapphi-red/vitepress-plugins/assets/27558987/e09bf78e-bb4d-4795-9225-f764d7cfea36)

**Comment by Suomm** [comment] 2023-11-22 14:54
tabs スタイルは公式 code-group と合わない.

**Comment by sapphi-red** [comment] 2023-11-23 10:50
It's because these plugin existed before the code-group feature was added.
PRs to change using the code-group feature for plugin-detype and plugin-npm-commands are welcome.

**Comment by sapphi-red** [comment] 2023-11-23 10:51
Duplicate of https://github.com/sapphi-red/vitepress-plugins/issues/12

**Closed by sapphi-red** 2023-11-23 10:51 UTC
